In [1]:
# the secret sauce 
# https://en.wikipedia.org/wiki/Naive_Bayes_classifier#Examples

In [2]:
# fitting method is calculating the mean and variance of x values

# predict method is what I already did, but replace x_i with the values 
# of x to be predicted

# final prediction is the sum of X[i] given those X values. 

In [3]:
import numpy as np
import pandas as pd

In [4]:
a = np.array([[-1, -1, 1], [-2, -1,1], [-3, -2,1], [1, 1,2], [2, 1,2], [3, 2,2]])
d = pd.DataFrame(a, columns=['x', 'x1', 'y'])
#b = np.array([1, 1, 1, 2, 2, 2])

In [5]:
d = pd.DataFrame(a, columns=['x', 'x1', 'y'])

In [6]:
d

x  x1  y
0 -1  -1  1
1 -2  -1  1
2 -3  -2  1
3  1   1  2
4  2   1  2
5  3   2  2

cheat sheat. Pandas Grouby https://jakevdp.github.io/PythonDataScienceHandbook/03.08-aggregation-and-grouping.html

In [7]:
e = d.groupby(by='y').var()

In [8]:
e

x        x1
y               
1  1.0  0.333333
2  1.0  0.333333

In [9]:
f = pd.DataFrame(e)

In [10]:
f

x        x1
y               
1  1.0  0.333333
2  1.0  0.333333

In [11]:
t = e

In [12]:
t.reset_index()

y    x        x1
0  1  1.0  0.333333
1  2  1.0  0.333333

In [13]:
e

x        x1
y               
1  1.0  0.333333
2  1.0  0.333333

In [14]:
e['x'][1]

1.0

In [15]:
f['x']

y
1    1.0
2    1.0
Name: x, dtype: float64

In [16]:
# create the fit method. Returns the dataframe containing the mean and variance.

# create the predict method manually and do calculations with it manually. 

# Once I have that, then work on automating the predict method as much as possible

In [17]:
a = np.array([[-1, -1, 1], [-2, -1,1], [-3, -2,1], [1, 1,2], [2, 1,2], [3, 2,2]])
d = pd.DataFrame(a, columns=['x', 'x1', 'y'])
#b = np.array([1, 1, 1, 2, 2, 2])

In [18]:
def fit(data, y):
  y = data[y]
  mean = data.groupby(by=y).mean()

  var = data.groupby(by=y).var()

  return mean, var

In [19]:
mean, var = fit(d, "y")

In [20]:
mean

x        x1
y               
1 -2.0 -1.333333
2  2.0  1.333333

In [21]:
var

x        x1
y               
1  1.0  0.333333
2  1.0  0.333333

In [22]:
def gnb(x_val, x_mean, x_var):
  # Variance of the x value in question
  x_var = x_var
  # x mean value
  x_mean = x_mean
  # natural log
  e = np.e
  # pi
  pi = np.pi
  # first part of the equation
  # 1 divided by the sqrt of 2 * pi * y_variance
  equation_1 = 1/(np.sqrt(2 * pi * x_var))
  
  # second part of equation implementation
  # denominator of equation
  denom = 2 * x_var

  # numerator calculation
  # the x value that is being used for computation
  x_val = x_val
  numerator = (x_val - x_mean) ** 2
  # the exponent
  expo = np.exp(-(numerator/denom))
  prob = equation_1 * expo

  return prob


In [23]:
# 0 = male
# 1 = female

In [24]:
df = pd.DataFrame({
    'y_person': [0,0,0,0,1,1,1,1],
    'height': [6, 5.92, 5.58, 5.92, 5, 5.5, 5.42, 5.75],
    'weight': [180,190,170,165,100,150,130,150],
    'foot': [12,11,12,10,6,8,7,9]
})

In [25]:
df

y_person  height  weight  foot
0         0    6.00     180    12
1         0    5.92     190    11
2         0    5.58     170    12
3         0    5.92     165    10
4         1    5.00     100     6
5         1    5.50     150     8
6         1    5.42     130     7
7         1    5.75     150     9

In [26]:
mean2, var2 = fit(df, 'y_person')

In [27]:
mean2

height  weight   foot
y_person                       
0         5.8550  176.25  11.25
1         5.4175  132.50   7.50

In [28]:
var2

height      weight      foot
y_person                                
0         0.035033  122.916667  0.916667
1         0.097225  558.333333  1.666667

In [29]:
# let's attempt to do a prediction

# sample data

# height = 6
# weight =  130
# foot = 8

In [30]:
# probability for height male
male_height_mean = mean2["height"][0]

# variance
male_height_var = var2['height'][0]

# male height probability
mhp = gnb(6, male_height_mean, male_height_var)
mhp

1.578883183264104

In [31]:
# probability for weight male
male_weight_mean = mean2["weight"][0]

# variance
male_weight_var = var2['weight'][0]

# male height probability
mwp = gnb(130, male_weight_mean, male_weight_var)
mwp

5.986743024812142e-06

In [32]:
# probability for foot male
male_foot_mean = mean2["foot"][0]

# variance
male_foot_var = var2['foot'][0]

# male height probability
mfp = gnb(8, male_foot_mean, male_foot_var)
mfp

0.0013112210442223452

In [33]:
# total male probability 

# probability of being male = 0.5

male_probability = mhp * mwp * mfp * 0.5
male_probability

6.197071843878078e-09

In [34]:
# probability for height female
female_height_mean = mean2["height"][1]

# variance
female_height_var = var2['height'][1]

# female height probability
fhp = gnb(6, female_height_mean, female_height_var)
fhp

0.22345872684481577

In [35]:
# probability for weight female
female_weight_mean = mean2["weight"][1]

# variance
female_weight_var = var2['weight'][1]

# female height probability
fwp = gnb(130, female_weight_mean, female_weight_var)
fwp

0.01678929788990836

In [36]:
# probability for foot female
female_foot_mean = mean2["foot"][1]

# variance
female_foot_var = var2['foot'][1]

# female height probability
ffp = gnb(8, female_foot_mean, female_foot_var)
ffp

0.286690699891019

In [37]:
# total female probability 

# probability of being female = 0.5

female_prop = fhp * fwp * ffp * 0.5
female_prop


0.0005377909183630018

In [38]:
# female

In [39]:
import sklearn

In [40]:
from sklearn.naive_bayes import GaussianNB

In [41]:
ga = GaussianNB()

In [42]:
x_values = pd.DataFrame({
    'height': [6, 5.92, 5.58, 5.92, 5, 5.5, 5.42, 5.75],
    'weight': [180,190,170,165,100,150,130,150],
    'foot': [12,11,12,10,6,8,7,9]
})

In [43]:
df

y_person  height  weight  foot
0         0    6.00     180    12
1         0    5.92     190    11
2         0    5.58     170    12
3         0    5.92     165    10
4         1    5.00     100     6
5         1    5.50     150     8
6         1    5.42     130     7
7         1    5.75     150     9

In [44]:
x_values

height  weight  foot
0    6.00     180    12
1    5.92     190    11
2    5.58     170    12
3    5.92     165    10
4    5.00     100     6
5    5.50     150     8
6    5.42     130     7
7    5.75     150     9

In [45]:
ga.fit(x_values, df['y_person'])

GaussianNB(priors=None, var_smoothing=1e-09)

In [46]:
df['y_person']

0    0
1    0
2    0
3    0
4    1
5    1
6    1
7    1
Name: y_person, dtype: int64

In [47]:
ga.theta_

array([[  5.855 , 176.25  ,  11.25  ],
       [  5.4175, 132.5   ,   7.5   ]])

In [48]:
ga.sigma_

array([[2.62757340e-02, 9.21875007e+01, 6.87500734e-01],
       [7.29194840e-02, 4.18750001e+02, 1.25000073e+00]])

In [49]:
z = np.array([6, 130, 8])
sample = pd.DataFrame({
    'height': [6],
    'weight': [130],
    'foot': [8]
})

sample

height  weight  foot
0       6     130     8

In [50]:
ga.predict(sample)

array([1])

In [51]:
n = np.array(x_values.groupby(by=df['y_person']).mean())

In [52]:
n

array([[  5.855 , 176.25  ,  11.25  ],
       [  5.4175, 132.5   ,   7.5   ]])

In [53]:
n[0][0]

5.855

In [54]:
len(np.unique(df['y_person']))

2

In [55]:
range(len(np.unique(df['y_person'])))

range(0, 2)

In [56]:
len(mean2)

2

In [57]:
m = np.array(mean2)
m

array([[  5.855 , 176.25  ,  11.25  ],
       [  5.4175, 132.5   ,   7.5   ]])

In [58]:
v = np.array(var2)
v

array([[3.50333333e-02, 1.22916667e+02, 9.16666667e-01],
       [9.72250000e-02, 5.58333333e+02, 1.66666667e+00]])

In [59]:
for i in range(len(m)):
  m_row = m[i]
  v_row = v[i]
  for a, b in enumerate(m_row):
    mean = b
    var = v_row[a]
    print(f'mean: {mean}, var: {var}')

mean: 5.855, var: 0.0350333333333333
mean: 176.25, var: 122.91666666666667
mean: 11.25, var: 0.9166666666666665
mean: 5.4175, var: 0.09722499999999994
mean: 132.5, var: 558.3333333333334
mean: 7.5, var: 1.6666666666666667


In [60]:
mean_var = []
#len_row = []
for i in range(len(m)):
  m_row = m[i]
  #len_row.append(len(m_row))
  v_row = v[i]
  for a, b in enumerate(m_row):
    mean = b
    var = v_row[a]
    mean_var.append([mean, var])

mean_var

[[5.855, 0.0350333333333333],
 [176.25, 122.91666666666667],
 [11.25, 0.9166666666666665],
 [5.4175, 0.09722499999999994],
 [132.5, 558.3333333333334],
 [7.5, 1.6666666666666667]]

In [61]:
n_class = len(np.unique(df['y_person']))
n_class

2

In [62]:
mean_var2 = np.array(mean_var)
mean_var2

array([[5.85500000e+00, 3.50333333e-02],
       [1.76250000e+02, 1.22916667e+02],
       [1.12500000e+01, 9.16666667e-01],
       [5.41750000e+00, 9.72250000e-02],
       [1.32500000e+02, 5.58333333e+02],
       [7.50000000e+00, 1.66666667e+00]])

In [63]:
# separate mean variance by class

s = np.vsplit(mean_var2, n_class)
s

[array([[5.85500000e+00, 3.50333333e-02],
        [1.76250000e+02, 1.22916667e+02],
        [1.12500000e+01, 9.16666667e-01]]),
 array([[5.41750000e+00, 9.72250000e-02],
        [1.32500000e+02, 5.58333333e+02],
        [7.50000000e+00, 1.66666667e+00]])]

In [64]:
s[0]

array([[5.85500000e+00, 3.50333333e-02],
       [1.76250000e+02, 1.22916667e+02],
       [1.12500000e+01, 9.16666667e-01]])

In [65]:
sample

height  weight  foot
0       6     130     8

In [66]:
mean_var

[[5.855, 0.0350333333333333],
 [176.25, 122.91666666666667],
 [11.25, 0.9166666666666665],
 [5.4175, 0.09722499999999994],
 [132.5, 558.3333333333334],
 [7.5, 1.6666666666666667]]

In [67]:
len(mean_var)

6

In [78]:
xs = [6, 130, 8]
# do this for the number of classes available

for i in range(n_class):
  # first class
  class_one = s[i]
  for i in range(len(class_one)):
    # first value in class one
    class_one_x_mean = class_one[i][0]
    class_one_x_var = class_one[i][1]
    x_value = xs[i]
    
    print([class_one_x_mean, class_one_x_var, x_value])


[5.855, 0.0350333333333333, 6]
[176.25, 122.91666666666667, 130]
[11.25, 0.9166666666666665, 8]
[5.4175, 0.09722499999999994, 6]
[132.5, 558.3333333333334, 130]
[7.5, 1.6666666666666667, 8]


In [69]:
xs = [6, 130, 8]
# do this for the number of classes available

# probabilities
prob = []
for i in range(n_class):
  # first class
  class_one = s[i]
  for i in range(len(class_one)):
    # first value in class one
    class_one_x_mean = class_one[i][0]
    class_one_x_var = class_one[i][1]
    x_value = xs[i]
    # now calculate the probabilities of each class. 
    prob.append([gnb(x_value, class_one_x_mean, class_one_x_var)])

    #print(class_one_x_mean, class_one_x_var, x_value)
prob

[[1.578883183264104],
 [5.986743024812142e-06],
 [0.0013112210442223452],
 [0.22345872684481577],
 [0.01678929788990836],
 [0.286690699891019]]

In [70]:
b = np.array(prob)
b

array([[1.57888318e+00],
       [5.98674302e-06],
       [1.31122104e-03],
       [2.23458727e-01],
       [1.67892979e-02],
       [2.86690700e-01]])

In [71]:
k = np.vsplit(b, n_class)
k

[array([[1.57888318e+00],
        [5.98674302e-06],
        [1.31122104e-03]]), array([[0.22345873],
        [0.0167893 ],
        [0.2866907 ]])]

In [72]:
prior = 1/n_class
prior


0.5

In [73]:
final_probabilities = []
for i in k:
  class_prob = np.prod(i) * prior
  final_probabilities.append(class_prob)

In [74]:
final_probabilities

[6.197071843878078e-09, 0.0005377909183630018]

In [75]:
maximum_prob = max(final_probabilities)
maximum_prob

0.0005377909183630018

In [76]:
u = np.unique(df['y_person'])
u

array([0, 1])

In [77]:
prob_index = final_probabilities.index(maximum_prob)
prediction = u[prob_index]
prediction

1